sonar.projectKey=oracle-university-analytics
sonar.projectName=Oracle University Analytics
sonar.sourceEncoding=UTF-8

sonar.sources=api,database,oracle-university-python-analytics,sh-sales-analytics,platform
sonar.tests=api
sonar.test.inclusions=api/test_*.py

sonar.exclusions=**/__pycache__/**,**/.venv/**,**/.venv-*/**,**/outputs/**,**/*.csv,**/*.joblib
sonar.python.coverage.reportPaths=api/coverage.xml
