SET SQLBLANKLINES ON

CREATE TABLE universities (
    university_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    university_code VARCHAR2(10) NOT NULL,
    university_name VARCHAR2(100) NOT NULL,
    city VARCHAR2(50) NOT NULL,
    founded_year NUMBER(4),
    website VARCHAR2(200),
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_universities PRIMARY KEY (university_id),
    CONSTRAINT uq_universities_code UNIQUE (university_code),
    CONSTRAINT ck_universities_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE faculties (
    faculty_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    university_id NUMBER NOT NULL,
    faculty_code VARCHAR2(10) NOT NULL,
    faculty_name VARCHAR2(100) NOT NULL,
    dean_name VARCHAR2(100),
    building_name VARCHAR2(100),
    phone VARCHAR2(20),
    email VARCHAR2(100),
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_faculties PRIMARY KEY (faculty_id),
    CONSTRAINT uq_faculties_code UNIQUE (faculty_code),
    CONSTRAINT fk_faculties_university
        FOREIGN KEY (university_id) REFERENCES universities (university_id),
    CONSTRAINT ck_faculties_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE departments (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    faculty_id NUMBER NOT NULL,
    department_code VARCHAR2(10) NOT NULL,
    department_name VARCHAR2(100) NOT NULL,
    head_name VARCHAR2(100),
    office_phone VARCHAR2(20),
    email VARCHAR2(100),
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_departments PRIMARY KEY (department_id),
    CONSTRAINT uq_departments_code UNIQUE (department_code),
    CONSTRAINT fk_departments_faculty
        FOREIGN KEY (faculty_id) REFERENCES faculties (faculty_id),
    CONSTRAINT ck_departments_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE students (
    student_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_id NUMBER NOT NULL,
    student_number VARCHAR2(20) NOT NULL,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(100),
    birth_date DATE,
    enrollment_year NUMBER(4) NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_students PRIMARY KEY (student_id),
    CONSTRAINT uq_students_number UNIQUE (student_number),
    CONSTRAINT uq_students_email UNIQUE (email),
    CONSTRAINT fk_students_department
        FOREIGN KEY (department_id) REFERENCES departments (department_id),
    CONSTRAINT ck_students_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'GRADUATED', 'SUSPENDED'))
);

CREATE TABLE instructors (
    instructor_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_id NUMBER NOT NULL,
    employee_number VARCHAR2(20) NOT NULL,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    academic_title VARCHAR2(50),
    email VARCHAR2(100),
    hire_date DATE,
    salary NUMBER(10,2),
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_instructors PRIMARY KEY (instructor_id),
    CONSTRAINT uq_instructors_employee UNIQUE (employee_number),
    CONSTRAINT uq_instructors_email UNIQUE (email),
    CONSTRAINT fk_instructors_department
        FOREIGN KEY (department_id) REFERENCES departments (department_id),
    CONSTRAINT ck_instructors_salary CHECK (salary IS NULL OR salary >= 0),
    CONSTRAINT ck_instructors_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE courses (
    course_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_id NUMBER NOT NULL,
    course_code VARCHAR2(20) NOT NULL,
    course_name VARCHAR2(100) NOT NULL,
    credits NUMBER(2) NOT NULL,
    course_level NUMBER(1) NOT NULL,
    description VARCHAR2(500),
    status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_courses PRIMARY KEY (course_id),
    CONSTRAINT uq_courses_code UNIQUE (course_code),
    CONSTRAINT fk_courses_department
        FOREIGN KEY (department_id) REFERENCES departments (department_id),
    CONSTRAINT ck_courses_credits CHECK (credits BETWEEN 1 AND 30),
    CONSTRAINT ck_courses_level CHECK (course_level BETWEEN 1 AND 8),
    CONSTRAINT ck_courses_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE TABLE semesters (
    semester_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    semester_code VARCHAR2(20) NOT NULL,
    academic_year VARCHAR2(20) NOT NULL,
    semester_name VARCHAR2(30) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR2(20) DEFAULT 'PLANNED' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_semesters PRIMARY KEY (semester_id),
    CONSTRAINT uq_semesters_code UNIQUE (semester_code),
    CONSTRAINT ck_semesters_dates CHECK (end_date > start_date),
    CONSTRAINT ck_semesters_status
        CHECK (status IN ('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE course_offerings (
    offering_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    course_id NUMBER NOT NULL,
    instructor_id NUMBER NOT NULL,
    semester_id NUMBER NOT NULL,
    section_code VARCHAR2(10) NOT NULL,
    classroom VARCHAR2(50),
    capacity NUMBER(4) DEFAULT 30 NOT NULL,
    schedule_day VARCHAR2(15),
    start_time VARCHAR2(5),
    end_time VARCHAR2(5),
    status VARCHAR2(20) DEFAULT 'OPEN' NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_course_offerings PRIMARY KEY (offering_id),
    CONSTRAINT uq_course_offerings
        UNIQUE (course_id, semester_id, section_code),
    CONSTRAINT fk_offerings_course
        FOREIGN KEY (course_id) REFERENCES courses (course_id),
    CONSTRAINT fk_offerings_instructor
        FOREIGN KEY (instructor_id) REFERENCES instructors (instructor_id),
    CONSTRAINT fk_offerings_semester
        FOREIGN KEY (semester_id) REFERENCES semesters (semester_id),
    CONSTRAINT ck_offerings_capacity CHECK (capacity > 0),
    CONSTRAINT ck_offerings_status
        CHECK (status IN ('OPEN', 'CLOSED', 'CANCELLED'))
);

CREATE TABLE enrollments (
    enrollment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    student_id NUMBER NOT NULL,
    offering_id NUMBER NOT NULL,
    enrollment_date DATE DEFAULT SYSDATE NOT NULL,
    enrollment_status VARCHAR2(20) DEFAULT 'ENROLLED' NOT NULL,
    attendance_rate NUMBER(5,2),
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_enrollments PRIMARY KEY (enrollment_id),
    CONSTRAINT uq_enrollments UNIQUE (student_id, offering_id),
    CONSTRAINT fk_enrollments_student
        FOREIGN KEY (student_id) REFERENCES students (student_id),
    CONSTRAINT fk_enrollments_offering
        FOREIGN KEY (offering_id) REFERENCES course_offerings (offering_id),
    CONSTRAINT ck_enrollments_status
        CHECK (enrollment_status IN ('ENROLLED', 'COMPLETED', 'DROPPED')),
    CONSTRAINT ck_enrollments_attendance
        CHECK (attendance_rate IS NULL OR attendance_rate BETWEEN 0 AND 100)
);

CREATE TABLE exams (
    exam_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    offering_id NUMBER NOT NULL,
    exam_name VARCHAR2(100) NOT NULL,
    exam_type VARCHAR2(30) NOT NULL,
    exam_date DATE NOT NULL,
    maximum_score NUMBER(6,2) DEFAULT 100 NOT NULL,
    weight_percentage NUMBER(5,2) NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_exams PRIMARY KEY (exam_id),
    CONSTRAINT fk_exams_offering
        FOREIGN KEY (offering_id) REFERENCES course_offerings (offering_id),
    CONSTRAINT ck_exams_max_score CHECK (maximum_score > 0),
    CONSTRAINT ck_exams_weight CHECK (weight_percentage BETWEEN 0 AND 100)
);

CREATE TABLE grades (
    grade_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    exam_id NUMBER NOT NULL,
    enrollment_id NUMBER NOT NULL,
    score NUMBER(6,2) NOT NULL,
    graded_at DATE DEFAULT SYSDATE NOT NULL,
    created_at DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_grades PRIMARY KEY (grade_id),
    CONSTRAINT uq_grades UNIQUE (exam_id, enrollment_id),
    CONSTRAINT fk_grades_exam
        FOREIGN KEY (exam_id) REFERENCES exams (exam_id),
    CONSTRAINT fk_grades_enrollment
        FOREIGN KEY (enrollment_id) REFERENCES enrollments (enrollment_id),
    CONSTRAINT ck_grades_score CHECK (score >= 0)
);
