SET LINESIZE 180
SET PAGESIZE 100
SET FEEDBACK ON
SET VERIFY OFF
SET SQLBLANKLINES ON
SET SERVEROUTPUT ON

COLUMN student_number FORMAT A12
COLUMN student_name FORMAT A25
COLUMN course_code FORMAT A10
COLUMN course_name FORMAT A35
COLUMN semester_code FORMAT A12

COLUMN first_name FORMAT A15
COLUMN last_name FORMAT A15
COLUMN department_name FORMAT A35

COLUMN exam_name FORMAT A30
COLUMN instructor_name FORMAT A25

COLUMN faculty_name FORMAT A35
COLUMN university_name FORMAT A40
